# 🐼 **AUPP Data Science Club**

## **Session 2: Python Basics for Data Science - NumPy & Pandas**

## Pandas Basics

What is Pandas? <br>

<img src="https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL3NodXR0ZXJzdG9jay0yMTIyNzcwNjctaGVyby5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOiIxMjAwIn19fQ==" width="600" alt="Pandas">

Not these pandas...

---

**Pandas** is a Python library used for data manipulation and analysis. It was built on top of the NumPy library

It allows users to clean, transform, merge, and filter rows and columns of data stored in tables or time series.

**Pandas** comes from **Pan**el **Da**ta

---

## Pandas Data Structures

There are 2 main data structures in Pandas:
- **Series**: 1D homogenous (single typed) array 
- **DataFrame**: 2D tabular structure with potentially heterogenous (different typed) columns

In [ ]:
%pip install pandas

### 2.1. Importing Pandas

In [1]:
import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 2.3.1

### 2.2. Series

It is basically a one-dimensional labeled array, representing a single column or row in a dataset.

In [2]:
# Create an empty Series
import numpy as np

empty_array = np.array([])

# Turn the array into Series
empty_series = pd.Series(empty_array)
empty_series

Series([], dtype: float64)

In [ ]:
arr = None
pd.Series(arr)

0      pen
1    pecil
2      bag
dtype: object

In [4]:
# We can also load data from dictionary
data = {'a': 10, 'b': 20, 'c': 30}

s = pd.Series(data)
s

a    10
b    20
c    30
dtype: int64

In [5]:
# Locate data using label
s.loc['a']

np.int64(10)

In [6]:
# Locate data using index
s.iloc[0]

np.int64(10)

### 2.3. DataFrame

we can think of a DataFrame as a bunch of Series objects put together to share the same index

In [83]:
# data of 10 employees (name, gender, title)
employees = {
    'name': ['Alice Chen', 'Ben Sok', 'Clara Lim', 'Daniel Wong', 'Emily Tran', 'Alex Sak',
             'Sophia Kim', 'Ryan Lee', 'Mia Chan', 'Kevin Lim'],
    'gender': ['F', 'M', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M'],
    'title': ['Data Analyst', 'Project Manager', 'Software Engineer', 'Data Engineer',
              'UI/UX Designer', 'Software Engineer', 'Data Analyst', 'Data Scientist',
              'Software Engineer', 'AI Engineer'],
    'age': [30, 28, 24, 24, 23, 27, 26, 29, 25, 31],
    'university': ['AUPP', 'RUPP', 'CamTech', 'RUPP', 'AUPP', 'PIU',
                   'AUPP', 'CamTech', 'ITC', 'PIU']
}

In [84]:
# Create a DataFrame called employees_df
employees_df = pd.DataFrame(employees)

employees_df

          name gender              title  age university
0   Alice Chen      F       Data Analyst   30       AUPP
1      Ben Sok      M    Project Manager   28       RUPP
2    Clara Lim      F  Software Engineer   24    CamTech
3  Daniel Wong      M      Data Engineer   24       RUPP
4   Emily Tran      F     UI/UX Designer   23       AUPP
5     Alex Sak      F  Software Engineer   27        PIU
6   Sophia Kim      F       Data Analyst   26       AUPP
7     Ryan Lee      M     Data Scientist   29    CamTech
8     Mia Chan      M  Software Engineer   25        ITC
9    Kevin Lim      M        AI Engineer   31        PIU

### 2.4. Row Manipulation

In [85]:
# Salary for the 10 employees
employees_salaries = [3000, 4000, 3500, 3800, 2500, 4200, 3200, 3200, 4000, 2500]

In [ ]:
# Create a new column called 'salary'

In [87]:
employees_df

          name gender              title  age university  salary
0   Alice Chen      F       Data Analyst   30       AUPP    3000
1      Ben Sok      M    Project Manager   28       RUPP    4000
2    Clara Lim      F  Software Engineer   24    CamTech    3500
3  Daniel Wong      M      Data Engineer   24       RUPP    3800
4   Emily Tran      F     UI/UX Designer   23       AUPP    2500
5     Alex Sak      F  Software Engineer   27        PIU    4200
6   Sophia Kim      F       Data Analyst   26       AUPP    3200
7     Ryan Lee      M     Data Scientist   29    CamTech    3200
8     Mia Chan      M  Software Engineer   25        ITC    4000
9    Kevin Lim      M        AI Engineer   31        PIU    2500

### 2.5. Column Deletion

In [88]:
# Drop 'university' column from employees_df, using .drop()
no_uni_df = employees_df.drop(columns='university')

no_uni_df

          name gender              title  age  salary
0   Alice Chen      F       Data Analyst   30    3000
1      Ben Sok      M    Project Manager   28    4000
2    Clara Lim      F  Software Engineer   24    3500
3  Daniel Wong      M      Data Engineer   24    3800
4   Emily Tran      F     UI/UX Designer   23    2500
5     Alex Sak      F  Software Engineer   27    4200
6   Sophia Kim      F       Data Analyst   26    3200
7     Ryan Lee      M     Data Scientist   29    3200
8     Mia Chan      M  Software Engineer   25    4000
9    Kevin Lim      M        AI Engineer   31    2500

### 2.6. Selecting Specific Rows

In [69]:
employees_df['title']     # Series
employees_df[['title']]   # DataFrame

               title
0       Data Analyst
1    Project Manager
2  Software Engineer
3      Data Engineer
4     UI/UX Designer
5  Software Engineer
6       Data Analyst
7     Data Scientist
8  Software Engineer
9        AI Engineer

In [ ]:
# Display only name, gender and title

          name gender              title
0   Alice Chen      F       Data Analyst
1      Ben Sok      M    Project Manager
2    Clara Lim      F  Software Engineer
3  Daniel Wong      M      Data Engineer
4   Emily Tran      F     UI/UX Designer
5     Alex Sak      F  Software Engineer
6   Sophia Kim      F       Data Analyst
7     Ryan Lee      M     Data Scientist
8     Mia Chan      M  Software Engineer
9    Kevin Lim      M        AI Engineer

### 2.7. Conditional Row Selection

Select only the rows that has the `True` value

In [90]:
# Select only the employees whose title is 'Software Engineer'
employees_df[employees_df['title'] == 'Software Engineer']

        name gender              title  age university  salary
2  Clara Lim      F  Software Engineer   24    CamTech    3500
5   Alex Sak      F  Software Engineer   27        PIU    4200
8   Mia Chan      M  Software Engineer   25        ITC    4000

In [ ]:
# Select only the employees who are Female

         name gender              title  age university  salary
0  Alice Chen      F       Data Analyst   30       AUPP    3000
2   Clara Lim      F  Software Engineer   24    CamTech    3500
4  Emily Tran      F     UI/UX Designer   23       AUPP    2500
5    Alex Sak      F  Software Engineer   27        PIU    4200
6  Sophia Kim      F       Data Analyst   26       AUPP    3200

### 2.8 Descriptive Statistics

In [92]:
# Statistics on age column
print("Age Statistics:")
print(f"  Count:    {employees_df['age'].count()}")
print(f"  Mean:     {employees_df['age'].mean()}")
print(f"  Median:   {employees_df['age'].median()}")
print(f"  Mode:     {employees_df['age'].mode().values}")
print(f"  Std Dev:  {employees_df['age'].std()}")
print(f"  Min:      {employees_df['age'].min()}")
print(f"  Max:      {employees_df['age'].max()}")

Age Statistics:
  Count:    10
  Mean:     26.7
  Median:   26.5
  Mode:     [24]
  Std Dev:  2.7507574714370344
  Min:      23
  Max:      31

In [ ]:
# Count the amount of each job title (using .value_counts())
title_amnt = None   # using .value_counts(), it also sorted for us in descending order (most value first)

title_amnt

title
Software Engineer    3
Data Analyst         2
Project Manager      1
Data Engineer        1
UI/UX Designer       1
Data Scientist       1
AI Engineer          1
Name: count, dtype: int64

#### Sorting

You can also do sorting operations, either sort by index or by value

In [ ]:
# Sort the amount of job title (use .sort_index() or .sort_values())

title
Software Engineer    3
Data Analyst         2
Project Manager      1
Data Engineer        1
UI/UX Designer       1
Data Scientist       1
AI Engineer          1
Name: count, dtype: int64

### 2.9. Data Inspection

In [79]:
# Find the information of our DataFrame
employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   gender      10 non-null     object
 2   title       10 non-null     object
 3   age         10 non-null     int64
 4   university  10 non-null     object
 5   salary      10 non-null     int64
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

In [93]:
# Get a Statistical Summary of our DataFrame
employees_df.describe()

             age       salary
count  10.000000    10.000000
mean   26.700000  3390.000000
std     2.750757   613.641227
min    23.000000  2500.000000
25%    24.250000  3050.000000
50%    26.500000  3350.000000
75%    28.750000  3950.000000
max    31.000000  4200.000000

### 2.11. Grouping Datasets

In [94]:
# Group Job Title by Gender (using .groupby())
title_by_gender = employees_df.groupby('gender')['title'].value_counts()

In [95]:
title_by_gender

gender  title
F       Data Analyst         2
        Software Engineer    2
        UI/UX Designer       1
M       AI Engineer          1
        Data Engineer        1
        Data Scientist       1
        Project Manager      1
        Software Engineer    1
Name: count, dtype: int64

In [96]:
# Find the average salary of each job title
    # Perform mean aggregation on education_info

salary_by_title = employees_df.groupby('title')['salary'].mean()

salary_by_title

title
AI Engineer          2500.0
Data Analyst         3100.0
Data Engineer        3800.0
Data Scientist       3200.0
Project Manager      4000.0
Software Engineer    3900.0
UI/UX Designer       2500.0
Name: salary, dtype: float64

### 2.12. I/O - Reading from and Writing to CSV files

Normally, reading a file is the initial step of doing data exploration.

Now, that we have our employee data set as `employees_df`, we can save it to a CSV file called `employee_dataset.csv`

In [99]:
path = 'employee_dataset.csv'

saved_file = employees_df.to_csv(path, index=False)

print("DataFrame has been saved at:", path)

DataFrame has been saved at: employee_dataset.csv

In [100]:
# Load our dataset back (using .read_csv())
df = pd.read_csv(path)

In [101]:
df

          name gender              title  age university  salary
0   Alice Chen      F       Data Analyst   30       AUPP    3000
1      Ben Sok      M    Project Manager   28       RUPP    4000
2    Clara Lim      F  Software Engineer   24    CamTech    3500
3  Daniel Wong      M      Data Engineer   24       RUPP    3800
4   Emily Tran      F     UI/UX Designer   23       AUPP    2500
5     Alex Sak      F  Software Engineer   27        PIU    4200
6   Sophia Kim      F       Data Analyst   26       AUPP    3200
7     Ryan Lee      M     Data Scientist   29    CamTech    3200
8     Mia Chan      M  Software Engineer   25        ITC    4000
9    Kevin Lim      M        AI Engineer   31        PIU    2500

In [ ]:
# Returns the first 5 rows of DataFrame (using .head())

          name gender              title  age university  salary
0   Alice Chen      F       Data Analyst   30       AUPP    3000
1      Ben Sok      M    Project Manager   28       RUPP    4000
2    Clara Lim      F  Software Engineer   24    CamTech    3500
3  Daniel Wong      M      Data Engineer   24       RUPP    3800
4   Emily Tran      F     UI/UX Designer   23       AUPP    2500

In [ ]:
# Returns the last 5 rows of DataFrame (using .tail())

         name gender              title  age university  salary
5    Alex Sak      F  Software Engineer   27        PIU    4200
6  Sophia Kim      F       Data Analyst   26       AUPP    3200
7    Ryan Lee      M     Data Scientist   29    CamTech    3200
8    Mia Chan      M  Software Engineer   25        ITC    4000
9   Kevin Lim      M        AI Engineer   31        PIU    2500